maize-genetics/phg_v2

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- CODE_OF_CONDUCT.md
Initial Commits of the project documents.  This also adds a template for Pull Requests which will take effect once it has been merged to main.
> Project basic docs

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRanges.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/resources/environment.yml
- version.properties
- [x ] I have performed a self-review of my code
syncing with master
```release-note
```
> sync utils_for_variants with master

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRanges.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/resources/environment.yml
- version.properties
- [x ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)
```release-note
syncing with master
```
> sync with master

- .github/workflows/phgv2_ci.yml
Fixing the CI to trigger at pull request update and also require code coverage minimums.
```release-note
```
> Fixing ci types

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/utils/VariantLoadingUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/InitdbTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/utils/VariantLoadingUtilsTest.kt
This adds in the unit tests for VariantLoadingUtils.  It currently does not test the gzipping and the indexing of the files as those require 3rd party tools which will need to be installed on the CI first.  Coverage is in the 85% range.
```release-note
Added in more error checking for the creation of VariantContexts and added in additional unit tests.
```
> Unit test variant loading utils

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/BuildRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/FastaGenerator.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/BuildMAFVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/BuildRefVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FastaGeneratorTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/IntegrationTestExtension.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/TestExtension.kt
Skeleton for a full Integration test for PHG 2.1.  I also added in some simple CLI based unit tests to verify the required parameters are in fact required.
```release-note
Added in the starting point for the Integration Test.
```
> Full integration test Skeleton

- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/InitdbTest.kt
```release-note
Added additional asserts to initdb test case
```
> addition to the junit test

- .github/workflows/phgv2_ci.yml
- src/main/kotlin/net/maizegenetics/phgv2/cli/SetupEnvironment.kt
Adding conda build to the CI.
```release-note
Adding conda builds to the CI workflow.
```
> Initial commit of adding conda to the CI build.

- .github/workflows/run_deploy_on_merge.yml
Adding in the conda build to the continuous delivery as well.
```release-note
Add conda to CD workflow.
```
> Add in Conda to the Continuous Delivery workflow as well.

- src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/utils/SeqUtilsTest.kt
```release-note
Additional AGC commands implemented
```
> implemented additional AGC commands

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
Bumping the version so we can work on a pre-release for 2.2.  I need a src change to trigger the build
```release-note
```
> Bumping up the version to 2.2 so I can trigger a pre-release.

- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/GeneralUtilities.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/VariantLoadingUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
```release-note
Verify sample names do not already exist  when adding new VCFs to datasets
```
> initial commit checking for duplicate sample names

- README.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/AlignAssembliesTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
```release-note
Updated parameters to align-assemblies
```
> Rename alignassemblies params

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/LoggingUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/TestExtension.kt
> Initial logging utils

- README.md
- data/test/smallseq/LineA.g.vcf
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/ExportVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
> Initdb update use minus n

- docs/hvcf_specifications.md
This PR updates how GT values are stored in hVCF files depending on haploid or diploid path finding.
```release-note
Updated GT values in hVCF spec to better reflect haploid and diploid path finding
```
> Updates to GT values in hVCF spec

- data/test/smallseq/LineImpute.h.vcf
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
```release-note
Fixed samplename usage when creating sequence from a paths hvcf file
```
> Altheader samplenames update

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
> Coded PHGv2 to return correct version

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt
> Chrom batching create fasta from hvcf

- src/main/kotlin/net/maizegenetics/phgv2/utils/FileUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/utils/FileUtilsTest.kt
> Buffered Reader and Writer

- README.md
- docs/imputation.md
- docs/terminology.md
This PR updates the README and terminology documentation to:
* Improve layout, organization, and grammar
* Add links to other vignettes and articles
```release-note
Updated README for layout and organization improvements and added links to other long form articles and vignettes
```
> Documentation - README cleanup

- docs/hvcf_region_handling.md
- docs/img/hvcf_region_handling/common_alignment.svg
- docs/img/hvcf_region_handling/fasta_regions.svg
- docs/img/hvcf_region_handling/inversion_handling.svg
- docs/img/inversion/inversion_handling.svg
This PR adds additional documentation about: 
* How haplotype regions are handled in PHG pipelines (specifically inversions)
* How this is recorded in hVCF files
```release-note
Added documentation regarding haplotype region handling
```
> Document haplotype region handling

- docs/build_and_load.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/InitdbTest.kt
```release-note
Resolved RAM issue with load-vcf by including option to increase anchor-gap size of TileDB-VCF databases
```
> Fix load vcf ram

- src/test/kotlin/net/maizegenetics/phgv2/brapi/api/SamplesTest.kt
> Added unit test for samples Endpoint with sampleDbId specified

- src/main/kotlin/net/maizegenetics/phgv2/agc/AnnotateFastas.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRanges.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/SetupEnvironment.kt
This PR adds descriptions to missing commands and general syntax cleanup. 
```release-note
Cleanup CLI help output
```
> Cleanup CLI help output

- docs/build_and_load.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/StartServer.kt
- src/main/resources/application.conf
- src/test/kotlin/net/maizegenetics/phgv2/cli/StartServerTest.kt
Added optional port parameter to start-server
```release-note
```
> Add port to start server

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateMafVCFTest.kt
Updated BioKotlin to v0.11. This changed gvcf generation, resulting in changes to hvcf generation that had to be incorporated.
A bug in hvcf generation was also discovered and fixed. 
```release-note
Updated BioKotlin version to 0.11 and fixed hvcf generation that broke as a result of the update
```
> Update maf vcf

- README.md
- docs/export_data.md
This PR adds documentation covering the current methods of export data from the PHG:
* Exporting VCF data from the TileDB instances
* Creating FASTA sequence data
* BrAPI-compliant server and a little discussion about rPHG2
```release-note
Added documentation about exporting data
```
> Documentation - exporting data

- README.md
This PR adds installation steps to the "Quick Start" section of the README. Testers found the current flow hard to follow.
```release-note
Add installation notes to "Quick Start" in README
```
> Add installation section to "Quick Start" section

- README.md
- docs/build_and_load.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/StartServer.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/VariantLoadingUtils.kt
- src/main/resources/application.conf
- src/test/kotlin/net/maizegenetics/phgv2/cli/AgcCompressTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateMafVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/ExportVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Gvcf2HvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/utils/SeqUtilsTest.kt
Made dbPath parameter optional - defaults to user's current working directory
```release-note
Made dbPath aprameter optional - defaults to user's current working directory.
```
> made dbPath parameter optional, couple document updates

- src/main/kotlin/net/maizegenetics/phgv2/pathing/MapKmers.kt
Fixing error Brandon found when testing Read Mappings
```release-note
Updating how file paths are handled in the Kmer Read Mapping code.
```
> Fixing relative path issue we noticed during scale testing.

- src/main/kotlin/net/maizegenetics/phgv2/pathing/FindPaths.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
> Imputation for full pipeline it

- docs/imputation.md
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndexTest.kt
Also updated BuildKmerIndex to follow other commands and updated the unit tests to match.
Updating docs and parameters for first 2 steps of imputation
```release-note
Fixing Build Kmer index Parameters so they are consistent with other commands.
```
> Adding in docs for kmer index and read mapping.  

- data/test/smallseq/LineA.h.vcf
- docs/build_and_load.md
- docs/export_data.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/brapi/BrapiSetupUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/ExportVcfTest.kt
Add option to pass a samples File instead of list for ExportVCF
```release-note
Added option to pass a file with sample names to ExportVcf
```
> Export from samples file

- docs/build_and_load.md
Add documentation clarification of agc-compress create vs append
```release-note
agc-compress documentation updated.
```
> update AGC documentation to explain create vs append

- docs/build_and_load.md
Update parameter name in documentation for LoadVcf
```release-note
Fixed parameter name for LoadVcf documentation
```
> update LoadVCF with correct parameter name vcf-dir

- docs/build_and_load.md
- src/main/kotlin/net/maizegenetics/phgv2/agc/AnnotateFastas.kt
- src/test/kotlin/net/maizegenetics/phgv2/agc/AnnotateFastasTest.kt
```release-note
Annotate fasta no longer compresses the new file as anchorwave needs uncompressed fastas
```
> Annotate fastas remove bgzip step

- docs/build_and_load.md
This PR provides general cleanup and helps improve context of the "Build and Load" steps of the documentation.
```release-note
Improve "Build and Load" documentation context
```
> Documentation - improve "Build and Load" context

- README.md
This PR replaces the pseudo-code with actual code for the imputation section of the quick start in the README file. 
```release-note
Update imputation quick start code in README
```
> Documentation - fix imputation quick start code in README

- src/main/resources/phg_environment.yml
```release-note
Set anchorwave version to 1.2.2 until we update BioKotlin to anchorwave's strand fix
```
> set anchorwave version in phg_environment.yml

- README.md
- docs/build_and_load.md
```release-note
Fixed documentation for gvcf2hvcf - corrected the parameter definitions.
```
> fixed gvcf2hvcf documentation

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/MergeHvcfs.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/MergeHvcfsTest.kt
> Merge hvcfs cli

- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/main/kotlin/net/maizegenetics/phgv2/rphg/RMethods.kt
- src/main/kotlin/net/maizegenetics/phgv2/rphg/RMethodsUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraphTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/rphg/RMethodsTest.kt
This PR:
* updates `RMethods.getHapIdMatrixFromGraph()` to include concurrency for optimized haplotype ID retrieval
* adds `RMethods.getAltHeaderPositionsFromGraph()` for JVM-side processing of all positional information from ALT header metadata. Tests showed ~15 seconds to return 1.4 million observations which _significantly_ reduces wait time (originally took several hours)
```release-note
Optimize R data retrieval methods for rPHG2
```
> Add faster R retrieval methods

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/PhgTest.kt
Added unit test for Phg.kt to increase code coverage
```release-note
Added unit test for Phg.kt to increase code coverage
```
> Unit test phg clikt

- data/test/smallseq/LineImputeMissingAH.h.vcf
- data/test/smallseq/LineImputeMissingHaps.h.vcf
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
```release-note
CreateFastaFromHvcfs fix hapid check to skip blank hapids indicating missing ref range
```
> allow blank hapids in CreateFastaFromHvcf

- src/main/kotlin/net/maizegenetics/phgv2/pathing/HaplotypeEmissionProbability.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/FindPathsTest.kt
> Fix null haplotype emission probability

- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/brapi/BrapiSetupUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/ExportVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/TestExtension.kt
```release-note
Changed export-vcf command to rename export files to have .g.vcf / .h.vcf extensions
```
> Export vcf extensions

- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateAnchorwaveDotplot.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/AlignAssembliesTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateAnchorwaveDotplotTest.kt
fixed relative path issue with ggsave() when called from AlignAssemblies for the dotplot
```release-note
fixed relative path issue with ggsave() when called from AlignAssemblies for the dotplot
```
> fixed ggsave() relative path problem.

- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
```release-note
added path parameter to ggsave to prevent unnecessary folder creation
```
> added path parameter to ggplot call

- src/main/kotlin/net/maizegenetics/phgv2/rphg/RMethods.kt
- src/test/kotlin/net/maizegenetics/phgv2/rphg/RMethodsTest.kt
This PR adds a new "ID" column to the data object containing reference range information. This will be needed to properly join between multiple tables on the R side.
```release-note
Add ID column to reference range data for rPHG2 evaluation
```
> rPHG2 - add ID to reference range data object

- docs/build_and_load.md
This PR fixes the following:
* Fix `Ref.sam` to `Ref.fa` found [here](https://github.com/maize-genetics/phg_v2/blob/67c0a5c954c730abbc30654d374c6bdb36867c18/docs/build_and_load.md?plain=1#L1157)
```release-note
Fix documentation typos
```
> Documentation - fix extension grammar

- data/test/smallseq/LineD.h.vcf
- data/test/smallseq/LineE.h.vcf
- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/FindPaths.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraphTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndexTest.kt
> BuildKmerIndex test for empty sampleContigList and map hapids to multiple ReferenceRanges

- README.md
- docs/build_and_load.md
This PR
* rearranges sections in the "Build and Load" documentation
* cleans up grammar
```release-note
Rearrange "Build and Load" documentation sections
```
> Rearrange doc sections in "Build and Load"

- docs/export_data.md
This PR
* Adds and expands on export commands and parameter usage.
```release-note
Update parameter usage in export documentation
```
> Update export command usage

- docs/build_and_load.md
- docs/export_data.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/StartServer.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/VariantLoadingUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/TileDBVcfReaderTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/AgcCompressTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateMafVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/FullPipelineIT.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Gvcf2HvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/InitdbTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/utils/SeqUtilsTest.kt
Add optional parameter condaEnvPrefix to all commands that use a ProcessBuilder that activates the conda environment
Add optional parameter condaEnvPrefix
```release-note
Added optional parameter conda-env-prefix to multiple commands
```
> chnages to include condaEnvPrefix for all ProcessBuilder calls

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/MergeGVCFs.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/MergeGVCFsTest.kt
```release-note
Added MergeGVCFs Clikt Command
```
> Merge gvcfs clikt command

- README.md
- docs/build_and_load.md
- docs/slurm_usage.md
This PR adds documentation related to using the `align-assemblies` command with the SLURM work scheduler.
```release-note
Add SLURM documentation
```
> Add SLURM usage sections

- docs/imputation.md
- src/main/kotlin/net/maizegenetics/phgv2/pathing/AlignmentUtils.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/MapKmers.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/AlignmentUtilsTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/MapKmersTest.kt
Updating Kmer Read Mapping to handle Kmers coming from different reference ranges.
```release-note
Update the Kmer Read Mapping to handle Kmers coming from multiple reference ranges.
```
> Multi ref range read mapping

- docs/build_and_load.md
This PR updates the quick-start parameters found within the "Build and Load" documentation.
```release-note
Fix quick-start parameters in "Build and Load" docs
```
> Fix "Build and Load" quick-start parameters

- src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt
FIxed bug effecting calculation of chromosome name from fasta id line
```release-note
Fixed bug related to identifying chrom name in fasta id line
```
> Fixed pulling chrom name from fasta idLine

- mkdocs.yml
This PR updates the project site URL to `phg.maizegenetics.net`
```release-note
Update site URL
```
> Update site URL

- docs/build_and_load.md
- docs/export_data.md
- docs/hvcf_region_handling.md
- docs/hvcf_specifications.md
- docs/imputation.md
- docs/installation.md
- docs/qc_metrics.md
- docs/slurm_usage.md
This PR:
* fixes admonition blocks to [conform to `mkdocs` format](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)
* fixes broken image links
* fixes miscellaneous formatting
```release-note
Fix mkdocs formatting bugs
```
> Fix formatting issues with mkdocs

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
```release-note
Added missing PrepareSlurmAlignFile() to Phg.kt to be user visible
```
> added PrepareSlurmAlignFile to Phg.kt

- docs/index.md
- docs/index_override/home.html
- docs/installation.md
- docs/stylesheets/extra.css
- mkdocs.yml
This PR:
* Updates the landing page background from linear gradient green (`#4cae4f`) to white (`#ffffff`) to just white
+ enhance text contrast
* Updates the tab element text to "bold"
* Updates the landing page title to "Welcome" instead of "Index"
* Updates the installation requirements from "Linux" to "Unix" OS
```release-note
Update landing page background color
```
> Fix site background and installation steps

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
```release-note
Parameters hvcf-file and hvcf-dir are mutually exclusive, and 1 must be provided on the command line.
```
> Merge hvcf file hvcf dir create fasta from hvcf

- src/main/kotlin/net/maizegenetics/phgv2/pathing/AlignmentUtils.kt
Updating map-kmer code to hopefully load in the index file faster.  I removed a section that did a class conversion which should speed things up by ~25% at a minimum.  I also reworked a bit of code which has a slight speed increase as it lowers number of temp objects created.
```release-note
Speeding up map-kmers steps.
```
> Speedup map kmers

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Gvcf2Hvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/utils/SeqUtils.kt
```release-note
Added condaEnvPrefix as optional parameter to Gvcf2Hvcf.
```
> add condaEnvPrefix to Gvcf2hvcf and places it is called

- docs/export_data.md
- [] `BUGFIX` (non-breaking change which fixes an issue)
```release-note
Updated documentation for the create-fasta-from-hvcf command
```
> update docs for create-fasta-from-hvcf to match code changes

- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
Fixing null Pointer error when building the Kmer index when trying to write out the diagnostic
```release-note
Fixing diagnostic error for build-kmer-index
```
> Fixing Build Kmer Index Diagnostic Error.

- docs/build_and_load.md
- docs/convenience_commands.md
- docs/export_data.md
- docs/hvcf_region_handling.md
- docs/hvcf_specifications.md
- docs/imputation.md
- docs/installation.md
- docs/ktor_specifications.md
- docs/qc_metrics.md
- docs/slurm_usage.md
- docs/terminology.md
- mkdocs.yml
This PR:
* Adds a new document: `convenience_commands.md`:
+ Describes supporting commands not found in other pipelines
* Fixes formatting issues with mkdocs:
+ unordered list indentation
+ certain code blocks not rendering
```release-note
Add "Convenience Command" docs
```
> Add "Convenience Command" docs

- docs/export_data.md
This PR fixes an indentation issue with one of the lists in `export_data.md`
```release-note
Fix list appearance in export docs 
```
> Fix list appearance in export docs

- src/main/kotlin/net/maizegenetics/phgv2/cli/SetupEnvironment.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/SetupEnvironmentTest.kt
> Setup env file not exist

- README.md
- docs/build_and_load.md
This PR:
* Updates the parameter usage for the command, `setup-environment` in the `build_and_load.md` documentation
* Updates the links on the README to link out to the new site
* Fix (_yet another_) enumeration issue on the site
```release-note
Update `setup-environment` docs
```
> Update `setup-environment` docs

- docs/build_and_load.md
- docs/convenience_commands.md
- docs/hvcf_specifications.md
This PR resolves some typos and formatting issues found within the documentation.
```release-note
General typo fixes
```
> General typo fixes

- src/main/kotlin/net/maizegenetics/phgv2/agc/PrepareAssemblies.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/AlignAssemblies.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CalcVcfMetrics.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateAnchorwaveDotplot.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRanges.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Gvcf2Hvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Hvcf2Gvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/LoadVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/PrepareSlurmAlignFile.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/MapKmers.kt
- src/test/kotlin/net/maizegenetics/phgv2/agc/PrepareAssembliesTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/AgcCompressTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/AlignAssembliesTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CalcVcfMetricsTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateAnchorwaveDotplotTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateRangesTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateRefVcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Gvcf2HvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Hvcf2GvcfTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/LoadVCFTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/PrepareSlurmAlignFileTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/MapKmersTest.kt
> change CliktCommands to use required() for required parameters

- docs/build_and_load.md
This PR adds a new admonition block further detailing the use (or lack thereof) of the `create-ranges` command.
```release-note
Add call-out for `create-ranges` command
```
> Add call-out for `create-ranges` command

- docs/build_and_load.md
This PR fixes a typo where the path to the reference file is missing in the quick start section for the `agc-compress` command.
```release-note
Fix reference file path typo
```
> Add reference file path

- src/main/kotlin/net/maizegenetics/phgv2/cli/AgcCompress.kt
While working on another feature, I noted an error in the AgcCompress:verifyFileAnnotation() function. FIxed the error but also re-wrote the function for efficiency.  Existing tests cover its execution.
```release-note
Fixed bug in AgcCompress:verifyFileAnnotation()
```
> verify AGC files bug fix

- docs/build_and_load.md
> Updates to build_and_load.md Quick Start

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateRanges.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Initdb.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/StartServer.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/FindPaths.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/MapKmers.kt
Add showDefaultValues=true to clikt help messages
```release-note
Add showDefaultValues=true to clikt help messages
```
> Add showDefaultValues=true to clikt help messages

- docs/imputation.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/ExportVcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/ExportVcfTest.kt
Changed imputation documentation to use export-vcf --sample-file instead of --sample-names.
Changed export-vcf parameter --outputDir to --output-dir
Added list-samples step to imputation documentation
```release-note
Improved imputation documentation
```
> Update export vcf

- docs/resequencing.md
Fixed command names which were incorrect in resentencing documentation
```release-note
Fixed command names in re-sequencing documentation
```
> fixed errors in quick start for reseq pipeline doc

- README.md
- docs/citations.md
- docs/stylesheets/extra.css
- mkdocs.yml
This PR adds a citation page emphasizing articles that deal with the PHG, either from our lab or adjacent labs that have built their own PHGs or have leverage data from the PHG.
```release-note
Add citation page
```
> Add "Citations" page

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
Updated CreateFastaFromHvcf string processing to improve performance
- [ x I have commented my code, particularly in hard-to-understand areas
```release-note
CreateFastaFromHVCF performance improvement
```
> Create fasta from hvcf oom

- docs/resequencing.md
This PR updates the resequencing documentation to better "flow" with the prior
"Building and Loading" and "Imputation" docs.
```release-note
Clean up resequencing documentation
```
> Update resequencing documentation

- README.md
- docs/imputation.md
Adding in a Disclaimer about the imputation issues currently facing the PHG. 
```release-note
Adding in Imputation Disclaimer Note.
```
> Impute disclaimer

- docs/build_and_load.md
- docs/convenience_commands.md
- docs/resequencing.md
- docs/variant_comparisons.md
- mkdocs.yml
* Adds page detailing @lynnjo's notes with some cleanup to various sections of the site
```release-note
Add variant comparisons page
```
> Add variant comparisons page

- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
Improve performance of HaplotypeGraph with Coroutines
```release-note
Improve performance of HaplotypeGraph with Coroutines
```
> Haplotype graph efficiency improvements

- docs/convenience_commands.md
- src/main/kotlin/net/maizegenetics/phgv2/cli/Hvcf2Gvcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Hvcf2GvcfTest.kt
```release-note
Added batching of vcf file exports to hvcf2gvcf command. Prevents tiledb from getting overwhelmed when exporting sample vcf files.
```
> Hvcf2gvcf update export

- src/main/kotlin/net/maizegenetics/phgv2/cli/Hvcf2Gvcf.kt
Fixed non-breaking issue with tiledb batched export command
```release-note
removed redundant data in tiledb batched export command
```
> fixed issue with hvcf2gvcf batched export command

- src/main/kotlin/net/maizegenetics/phgv2/pathing/ImputationMetrics.kt
Added columns RefLen and HaplotypeLen to the ImputationMetrics output
```release-note
Added RefLen and HaplotypeLen columns to ImputationMetrics output
```
> added ref and chosen haplotype len to ImputationMetrics

- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraphTest.kt
Whole graph checksum
```release-note
Whole graph checksum
```
> Whole graph checksum

- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/test/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraphTest.kt
Added method HaplotypeGraph.refChecksum()
```release-note
Added method HaplotypeGraph.refChecksum()
```
> Checksum for ref seq at range

- docs/convenience_commands.md
- docs/hvcf_specifications.md
* Updates the "Convenience Commands" documentation
+ Adds new "summary stats" commands made by @tcasstevens and @lynnjo 
+ Adds new navigable section header
* Updates VCF specifications to match current `v2.4` specs, specifically with the `##ALT` header section.
```release-note
```
> Update commands and VCF specification

- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
Added missing parameter to createASMHvcfs() call
```release-note
Fixed bug in CreateMafVcf when legacy-maf-file is true
```
> added missing flag to CreateMafVcf:createASMHvcfs()

- src/main/kotlin/net/maizegenetics/phgv2/pathing/AlignmentUtils.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/KmerIndexStatistics.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/MapKmersTest.kt
Added the graph has to the kmerIndex.txt file, along with graph comparison checks to MapKmers.kt
```release-note
Added graph checksum value to kmerIndex.txt file as well as comparison checking of graph to map-kmers
```
> add graph hash to kmer processing

- src/main/kotlin/net/maizegenetics/phgv2/rphg/RMethods.kt
- src/test/kotlin/net/maizegenetics/phgv2/rphg/RMethodsTest.kt
* Adds reference range sequence checksum column (`rr_checksum`) to `RList` return from `getRefRangesFromGraph()` method
+ This is used in rPHG2 and returned as a [`GRanges`](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003118) object for enhanced querying in R.
```release-note
Add checksum column for getRefRangesFromGraph() return object (rPHG2 functionality)
```
> Add checksum column for reference range table

- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfRangeFastaTest.kt
Added method HaplotypeGraph. hapidToSeqLength()
```release-note
Added method HaplotypeGraph. hapidToSeqLength()
```
> Graph hapid seqlen

- docs/resequencing.md
- mkdocs.yml
* Adds details about creating an index file for the composite assembly (needed for the DeepVariant steps)
* Fixes color bug for navbar
```release-note
Add indexing step to "Resequencing" documentation
```
> Add indexing step to "Resequencing" documentation

- docs/imputation.md
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
Updating kmer indexing to not throw an error if the discard set is too full.  Also allow the user to control the amount of filtering done to the Kmers.
```release-note
Updating Kmer indexing to allow for user control of discard set and to use the BigLongSet if requested.
```
> Update kmer index large discard

- src/main/kotlin/net/maizegenetics/phgv2/brapi/service/VariantSetsService.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcf.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/HapidSampleTable.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/MergeHvcfs.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/SampleHapidByRange.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/BuildKmerIndex.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ExtractEdgeReads.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/FindPaths.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/KmerIndexStatistics.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/MapKmers.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/QcReadMapping.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/CreateFastaFromHvcfRangeFastaTest.kt
Changed usages of HaplotypeGraph to use inputDir constructor to simplify the code
```release-note
Changed usages of HaplotypeGraph to use inputDir constructor to simplify the code
```
> Graph dir constructor

- data/test/ropebwt/LineA_FullChr.bed
- data/test/ropebwt/testHVCFs/LineA.h.vcf
- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CliktLogging.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRm2Ps4gFile.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRopebwt2Ps4gFile.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertVcf2Ps4gFile.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/MapReads.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/PS4GUtils.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/RopeBWTUtils.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRm2Ps4gFileTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRopebwt2Ps4gFileTest.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/MapReadsTest.kt
Initial versions of the Positional Support for Gamete file creators.  Right now ReadMapping and RopeBWT3 can be used as inputs
```release-note
Adding in PS4G file creation
```
> Hackathon impute

- mkdocs.yml
* Updates the project copyright to current year
```release-note
Bump copyright date
```
> Bump copyright date

- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRopebwt2Ps4gFile.kt
- src/test/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/ConvertRopebwt2Ps4gFileTest.kt
* Updates spline interpolator to use the [Akima algorithm](https://commons.apache.org/proper/commons-math/javadocs/api-3.6.1/org/apache/commons/math3/analysis/interpolation/AkimaSplineInterpolator.html)
* Fixes exceptions in spline interpolation tests caused by change to new interpolator
+ Adds more observations
```release-note
Update spline interpolation to the Akima algorithm
```
> Update spline interpolation to use the Akima algorithm (1970)

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/cli/CliktLogging.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/CreateMafVcf.kt
> Updated dependency BioKotlin from version 0.22 to 0.25

- build.gradle.kts
- src/main/kotlin/net/maizegenetics/phgv2/brapi/service/VariantsService.kt
```release-note
Removing PHGv2 dependence on ehcache
```
> Remove ehcache depend

- README.md
- docs/build_and_load.md
- docs/imputation.md
- docs/imputation_ropebwt.md
- mkdocs.yml
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/MapReads.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/RopeBwtIndex.kt
```release-note
Update documentation to make RopeBWT Imputation the preferred method
```
> Change documentation to make RopeBWT Imputation the preferred method

- data/test/exportGraph/testMultipleFilesHaplotypeGraph.vcf
- data/test/exportGraph/testMultipleFilesHaplotypeGraphRangeSampleGamete.vcf
- data/test/exportGraph/testSingleSampleHaplotypeGraph.vcf
- data/test/exportGraph/testSingleSampleHaplotypeGraphRangeSampleGamete.vcf
- src/main/kotlin/net/maizegenetics/phgv2/api/ExportHaplotypeGraph.kt
- src/main/kotlin/net/maizegenetics/phgv2/api/HaplotypeGraph.kt
- src/main/kotlin/net/maizegenetics/phgv2/cli/Hvcf2Gvcf.kt
```release-note
Adds ##contig lines to HVCF header when exporting from HaplotypeGraph
```
> Contigs missing from hvcfs

- docs/convenience_commands.md
- docs/imputation_ropebwt.md
* Adds information about the `rope-bwt-chr-index` command
* Minor appearance tweaks
```release-note
Add information about chromosome indexer command for ropebwt3
```
> Add information about chromosome indexer command for ropebwt3

- src/main/kotlin/net/maizegenetics/phgv2/cli/Hvcf2Gvcf.kt
- src/test/kotlin/net/maizegenetics/phgv2/cli/Hvcf2GvcfTest.kt
```release-note
Added coroutines to exporting GVCF files
```
> Hvcf to gvcf performance

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
Adding back in Imputation Metrics to the CLI.
```release-note
Adding ImputationMetrics back into PHG CLI.
```
> Adding back in ImputationMetrics

- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/BuildSplineKnots.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/SplineUtils.kt
First speed change to the spline code.  This fixes the downsample point code to be a lot faster.
```release-note
Speeding up Spline Creation
```
> Spline speed changes

- src/main/kotlin/net/maizegenetics/phgv2/cli/Phg.kt
- src/main/kotlin/net/maizegenetics/phgv2/pathing/ropebwt/MapReadsFromBed.kt
Allow users to write a read mapping file directly from the BED file from ropebwt3
```release-note
Adding in bed to read mapping command.
```
> Initial commit of bed file to read mapping code
